

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
   - job: job1
     steps:
     - bash: echo job1
     - bash: echo $(PipelineLevelVaribale)
   - job: job2
     steps:
     - bash: echo job2
- stage: DevDeploy
  variables:
   environment: DEV
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - bash: echo $(environment) Deploy
- stage: QADeploy
  variables:
   environment: QA
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(environment) Deploy
- stage: ProdDeploy
  variables:
   environment: PROD
  dependsOn: 
   - DEVDeploy
   - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo $(environment) Deploy

