

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
   - job: job1
     steps:
     - bash: echo job1
   - job: job2
     steps:
     - bash: echo job2
- stage: DevDeploy
  jobs:
  - job: DEVDeployJob
    steps:
    - bash: echo DEV Deploy
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QA Deploy
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Prod Deploy

